Implement propagate methods
LimeChain/filecoin-ipc-actors-fevm pull request #32
Opened 2023-03-31 08:38 UTC by arrusev

2023-03-31 08:39 UTC, arrusev commented
Current dependencies on/for this PR:
* main
  * **PR #22** <a href="https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/22" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #30** <a href="https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/30" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #31** <a href="https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/31" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #32** <a href="https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/32" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/32?utm_source=stack-comment).

2023-04-21 12:50 UTC, 2dpetkov commented on src/Gateway.sol
> +        PostboxItem memory postboxItem = postbox[postboxId];
`postboxItem` can be referenced from `storage`

2023-04-21 12:50 UTC, 2dpetkov commented on src/Gateway.sol
> +        uint256 postboxId = postboxCidToId[postboxCid];
optimisation suggestion: (both here and in `propagate`), we fetch `postboxId` 3 times and `postboxItem` twice.
We can translate `onlyPostboxOwner` and `onlyValidPostboxId` modifiers to `_checkX` functions and spare ourselves some opcodes. Or else - write the `require`'s directly in the code.

2023-04-21 12:50 UTC, 2dpetkov commented on src/Gateway.sol
> +    function whitelistPropagator(
please add `/// @notice`

2023-04-21 12:50 UTC, 2dpetkov commented on src/Gateway.sol
> +    function propagate(
please add `/// @notice`

2023-04-21 12:50 UTC, 2dpetkov commented on src/Gateway.sol
> +        payable(msg.sender).sendValue(msg.value - crossMsgFee);
is there a case when we `msg.value` will be equal to the fee? We will have `hasFee` failing then, of course, and I am wondering if that's okay.

2023-04-21 12:50 UTC, 2dpetkov commented on src/interfaces/IGateway.sol
> +    function propagate(bytes32 postboxCid) external payable;
Please add NatSpec

2023-04-21 12:50 UTC, 2dpetkov commented on src/structs/Postbox.sol
> +import "openzeppelin-contracts/utils/structs/EnumerableSet.sol";
can be removed

2023-04-24 12:20 UTC, arrusev commented on src/Gateway.sol
> +        payable(msg.sender).sendValue(msg.value - crossMsgFee);
It's not okay, you are right. There could be a such case where the `msg.value` is equal to the `fee`. If there is a remaining fee, only then we should send it back to the sender, otherwise do nothing.

2023-04-24 12:24 UTC, arrusev commented on src/Gateway.sol
> +        uint256 postboxId = postboxCidToId[postboxCid];
we can do a combination of both approaches. 
A getter method with require in it(safe getter). wdyt?

2023-04-24 15:30 UTC, 2dpetkov commented on src/Gateway.sol
> +        uint256 postboxId = postboxCidToId[postboxCid];
nice!

2023-04-25 07:05 UTC, 2dpetkov approved these changes

2023-04-25 08:32 UTC, adlrocha requested changes
I just realized there may be a conceptual mistake, propagate expects the CID of a cross-net message as an input, not that of the postboxItem object (maybe I misunderstood something)

2023-04-25 08:32 UTC, adlrocha commented on src/Gateway.sol
> +    function propagate(bytes32 postboxCid) external payable {
This Cid shouldn't be the one for the postbox item, but that of the cross-net message that wants to be propagated from the postbox.

2023-04-25 08:39 UTC, adlrocha requested changes
LGTM apart from the thing that I mentioned in the previous PR. Unless I have misunderstood something, the postbox and postbox items don't need to be indexed by unique id, the `Cid` that we use to identify messages queued for propagation is the `Cid` of the message being queued. That means that `propagate` and `whitelistPropagator` should accept as an argument the Cid of the cross-net message that wants to be propagated further. 

Let me know if this is not clear, we can discuss sync in Slack or with quick huddle. Thanks!

2023-04-25 08:39 UTC, adlrocha commented on src/Gateway.sol
> +        bytes32 newPostboxCid = postboxItem.toHash();
Why do you need to re-compute the cid of the postbox? The postbox is used to queue cross-messages that need to be propagated further. The index used to identify an item of the postbox is through the cid of the message queued for propagation. Adding owners to the postbox item shouldn't trigger a change to the hash of the postbox message (nothing changes in the message).

2023-04-25 08:39 UTC, adlrocha commented on src/Gateway.sol
> +                postboxItem.owners.push(owner);
Why do we need to push the owner here? Wouldn't it be enough by tracking it in `postboxHasOwner`?

2023-04-25 12:35 UTC, arrusev commented on src/Gateway.sol
> +                postboxItem.owners.push(owner);
We were pushing it to the array, so to be able to recalculate the cid of the postbox but it's not needed anymore.

2023-04-25 12:58 UTC, adlrocha approved these changes
LGTM. Just a quick nit to rename the argument for the function (and maybe throughout the code, as using `postboxID` maybe a bit confusing, because there is no ID for the postbox. Apart from that, feel free to merge. Thanks for the fix.

2023-04-25 12:58 UTC, adlrocha commented on src/Gateway.sol
> +        bytes32 postboxId,
Maybe rename throughout the code? There is no specific ID for the postbox, and it may be confusing to use `postboxID`. The postbox is the queue of messages that need to be propagated, but the postbox in itself doesn't  have an ID. 
```suggestion
        bytes32 msgCid,
```

2023-04-25 12:58 UTC, adlrocha commented on src/interfaces/IGateway.sol
> +    function whitelistPropagator(bytes32 postboxId, address[] calldata owners)
```suggestion
    function whitelistPropagator(bytes32 msgCid, address[] calldata owners)
```

2023-04-25 12:58 UTC, adlrocha commented on src/interfaces/IGateway.sol
> +    function propagate(bytes32 postboxId) external payable;
```suggestion
    function propagate(bytes32 msgCid) external payable;
```

2023-04-25 19:18 UTC, 2dpetkov submitted a review, later dismissed

2023-04-26 07:03 UTC, mikirov submitted a review, later dismissed

2023-04-26 07:20 UTC, mikirov approved these changes
LGTM

2023-04-26 07:21 UTC, merged