deployment-and-coverage
LimeChain/filecoin-ipc-actors-fevm pull request #47
Opened 2023-05-29 11:14 UTC by mikirov

2023-05-29 11:14 UTC, mikirov commented
Current dependencies on/for this PR:
* main
  * **PR #47** <a href="https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/47" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/LimeChain/filecoin-ipc-actors-fevm/47?utm_source=stack-comment).

2023-06-06 08:55 UTC, arrusev approved these changes
LGTM. Leaving 2 chores

2023-06-06 08:55 UTC, arrusev commented on src/Gateway.sol
> +import "forge-std/console.sol";
we can remove the forge console import

2023-06-06 15:54 UTC, adlrocha requested changes
The PR is huge, it was quite hard to catch all of the details.  A few comments: 
- Can we add a README in the `scripts` folder explaining the scripts available and the instructions to deploy the contracts (or in the main repo README)?
- Also, the argument for `join` should be a network address, not a blockchain/crypto address

2023-06-06 15:54 UTC, adlrocha commented on src/SubnetActor.sol
> +    function join(address validator) external payable signableOnly notKilled {
This is not an `address` in terms of crypto address  but a network address that needs to be persisted along with the validator information like we do in the rust actors: https://github.com/consensus-shipyard/ipc-actors/blob/afbc88798a8558954c3a7403cc1e0281b8ad0429/subnet-actor/src/types.rs#L27
```suggestion
    function join(string validator) external payable signableOnly notKilled {
```

2023-06-07 08:34 UTC, adlrocha approved these changes
LGTM

2023-06-08 06:55 UTC, merged